"""clothing shop: product_tags table, category/size/color

Revision ID: bcce0dd4d991
Revises: 902dcad362e1
Create Date: 2026-07-06 16:57:00.428876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcce0dd4d991'
down_revision: Union[str, None] = '902dcad362e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfc_tag_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_tags_nfc_tag_id'), 'product_tags', ['nfc_tag_id'], unique=True)
    op.add_column('products', sa.Column('category', sa.String(length=60), nullable=True))
    op.add_column('products', sa.Column('size', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('color', sa.String(length=40), nullable=True))
    op.drop_index('ix_products_nfc_tag_id', table_name='products')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    # Port existing single-tag registrations into the new table before
    # dropping the column, so already-registered stickers keep working.
    op.execute(
        "INSERT INTO product_tags (nfc_tag_id, product_id) "
        "SELECT nfc_tag_id, id FROM products WHERE nfc_tag_id IS NOT NULL"
    )
    op.drop_column('products', 'nfc_tag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('nfc_tag_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # Restore one tag per product (extra tags beyond the first are lost).
    op.execute(
        "UPDATE products SET nfc_tag_id = ("
        "SELECT nfc_tag_id FROM product_tags "
        "WHERE product_tags.product_id = products.id ORDER BY id LIMIT 1)"
    )
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_index('ix_products_nfc_tag_id', 'products', ['nfc_tag_id'], unique=True)
    op.drop_column('products', 'color')
    op.drop_column('products', 'size')
    op.drop_column('products', 'category')
    op.drop_index(op.f('ix_product_tags_nfc_tag_id'), table_name='product_tags')
    op.drop_table('product_tags')
    # ### end Alembic commands ###
